### ISSUE TITLE
Add Windows 11 troubleshooting

### ISSUE THREAD

**Issue by adrianstevens** [WildernessLabs/Documentation#282]
Anything from the community?

**Comment by patridge** [comment]
fwiw, the only issue I had was when something I installed prior to Meadow tools on a fresh Windows 11 system created a NuGet.config file with an empty `packageSources` entry (?VS Code, maybe?). That prevented me from doing the `dotnet tool install` because nothing could be found that wasn't already cached locally.

I ended up copying a proper NuGet.config from an old machine, but there are probably other ways to get a new default one generated. And it's possible this could affect a fresh Windows 10 install, too.

**Comment by patridge** [comment]
And...while I didn't have WinUSB already installed as the driver for the DFU Meadow board, it didn't have the STTub30 driver there either. It just had no driver.

**Comment by patridge** [comment]
Given Windows 11 has been out for a while now (Oct 2021, when this was filed), closing this until something specific comes up.
